channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - cython
  - numpy>=1.4
  - scip
  - pip
  - pip:
    - git+https://github.com/ds4dm/PySCIPOpt.git@ecole-benchmark
    - git+https://github.com/ds4dm/learn2branch@v1.0.0
  - jupyter
  - ipywidgets
  - scipy
  - pandas
  - matplotlib
  - seaborn
